N=10^5;
ModOrder=8;
data = randint(1,N,ModOrder);
data_mod = pammod(data,ModOrder);
UpsampleFactor = 4;
data_mod_upsam = [data_mod;zeros(UpsampleFactor-1,length(data_mod))];
data_mod_upsam = data_mod_upsam(:);
Tsym = 1;
RRCFiltLen = 8;
beta = 1;
t = -RRCFiltLen/2:1/UpsampleFactor:RRCFiltLen/2;
numer = sin(pi*t*(1-beta)/Tsym)+((4*beta*t/Tsym).*cos(pi*t*(1+beta)/Tsym));
denom = pi*t.*(1-(4*beta*t/Tsym).^2)/Tsym;
hFilt = 1/sqrt(Tsym)*numer./denom;
hFilt(ceil(length(hFilt)/2)) = 1/sqrt(Tsym)*((1-beta)+4*beta/pi);
hFilt(t==Tsym/(4*beta)) = (beta/sqrt(2*Tsym))*((1+2/pi)*sin(pi/4*beta))+ ((1-2/pi)*cos(pi/(4*beta)));
hFilt(t==-Tsym/(4*beta)) = (beta/sqrt(2*Tsym))*((1+2/pi)*sin(pi/4*beta))+ ((1-2/pi)*cos(pi/(4*beta)));
EbN0dB = 10;
snr = 10*log10(log2(ModOrder))+EbN0dB;
RxSym = awgn(data_mod_upsam,snr);
MatchedFiltOut = conv(RxSym,hFilt);
MatchedFiltOutUp = interp(MatchedFiltOut,UpsampleFactor);
NumOfSampInSym = 24;
NumOfTraces = 100;
Vals = reshape(MatchedFiltOutUp(UpsampleFactor*FilterDelay + 1: (UpsampleFactor*FilterDelay + UpsampleFactor*NumOfSampInSym*NumOfTraces)),UpsampleFactor*NumOfSampInSym,NumOfTraces);
%Vals = reshape(MatchedFiltOutUp(FilterDelay + 1: (FilterDelay + NumOfSampInSym*NumOfTraces)),NumOfSampInSym,NumOfTraces);
timeBase = (0:1:UpsampleFactor*NumOfSampInSym -1)/UpsampleFactor^2;
%timeBase = (0:1:NumOfSampInSym -1)/UpsampleFactor;
plot(timeBase,Vals);
